language: ruby
cache: bundler
rvm:
  - 2.7.4

script: ./script/cibuild

# Branch blacklist, exclude branches that are not Github Pages
branches:
  except:
  - base

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

notifications:
  email: false
