# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Project Electron
email: your-email@domain.com
author: Your Name
description: This website is the home of all news regarding the Rockefeller Archive Center and Marist College IT's Project Electron.
copyright: 'Copyright &copy; 2016 Rockefeller Archive Center. All Rights Reserved.'
credits: 'Based on Landing Page theme by <a href="http://startbootstrap.com/">Start Bootstrap</a>. Lightning photo by <a href="
https://www.flickr.com/photos/ribarnica/">ribarnica</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/rockarch_org
  - title: github
    url: https://github.com/RockefellerArchiveCenter
