name: update dependencies
on:

  schedule:
    - cron:  '0 0 1 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - run: bundle update --all && bundle install

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: gh-pages
          branch: dependency-updates
          delete-branch: true
          title: Dependency Updates
          commit-message: Dependency updates
